### ISSUE TITLE
to use for other scripting language

### ISSUE THREAD

**Issue by rahulsng700** [ValYouW/ml-ocr-tool#3]
hi. i found this project very helpful for my project. i want to create my own custom dataset of digits of a language. And i wanted to use your project to classify my digits from inputshit.docx . i was planing take the print of this sheet and write numbers in row wise.. like 0 for first row,1 for second row, and so on. 
can i use this project to classify all the images after scanned, as 0 for first row, 1 for second row and so on in excel sheet?

**Comment by rahulsng700** [comment]
<img width="975" alt="Screenshot 2021-03-21 at 2 06 16 PM" src="https://user-images.githubusercontent.com/40354507/111898897-e5a7e580-8a4e-11eb-8f6f-eb3a5b246481.png">

I was hoping to extract this image and convert it into cropped single images with label of 0s for first row,1s for second row,and so on.. ofcourse i am going to print the blank sheet with 10 rows and i am going to write manually for the language i have chosen, and get scanned of that sheet and pass it to your project. and hoping to get the classified file containing the images with respective labels.

**Comment by ValYouW** [comment]
wow it was long long time ago, I don't remember a lot from this project, just take a look at the code if see if you can make adjustments...

**Comment by rahulsng700** [comment]
Okh.. thanks though
